# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################


- arguments: [-XGHC2021, -XOverloadedStrings]


##########################
# Custom hints

# Use context with site-specific customizations.
- warning: {lhs: defaultContext, rhs: siteContext}

# siteContext is defined in terms of defaultContext.
# Do not warn about the use of defaultContext in this definition.
- ignore: {name: Use siteContext, within: Web.Site.Compilers}
