name:                personal
version:             0.0.0
github:              "chungyc/site-personal"
homepage:            "https://chungyc.org/"
author:              "Yoo Chung"
maintainer:          "web@chungyc.org"
license:             "AllRightsReserved"
copyright:           "Copyright (C) 2023 Yoo Chung"

# Metadata used when publishing your package
synopsis:            Personal web site for Yoo Chung
category:            Personal

description: |
  Library for generating the personal web site belonging to [Yoo Chung](https://chungyc.org/).
  .
  * The URL for the site is <https://chungyc.org/>.
  .
  * Some guidance on [how to use the library](https://chungyc.org/article/technical/website/guide) is also available.
  .
  * The source is available on [GitHub](https://github.com/chungyc/site-personal).

language: GHC2021

default-extensions:
- OverloadedStrings

ghc-options:
- -Wall
- -Werror

dependencies:
- base

library:
  source-dirs: src
  dependencies:
  - hakyll
  - bytestring
  - diagrams-lib
  - diagrams-svg
  - filepath
  - http-types
  - pandoc
  - svg-builder
  - text
  - wai
  - wai-app-static

executables:
  site:
    main: app/Site.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - personal
    - hakyll
    # Not directly depended upon by the executable,
    # but included here to ensure these are available
    # for site Haskell code which generate files.
    - clay
    - diagrams-contrib
    - diagrams-lib
    - diagrams-svg

tests:
  examples:
    main: test/Examples.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - personal
    - doctest-parallel
