name:                personal
version:             0.0.0
github:              "chungyc/site-personal"
homepage:            "https://chungyc.org/"
author:              "Yoo Chung"
maintainer:          "yoo.chul.chung@gmail.com"
license:             "AllRightsReserved"
copyright:           "Copyright (C) 2023 Yoo Chung"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Personal web site for Yoo Chung
category:            Personal

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Source for personal web site which belongs to Yoo Chung.

language: GHC2021

default-extensions:
- OverloadedStrings

ghc-options:
- -Wall

dependencies:
- base

library:
  source-dirs: src
  dependencies:
  - hakyll
  - clay

executables:
  site:
    main:                app/Site.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - personal
    - hakyll
  style:
    main:                app/Style.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - personal
    - clay
    - text

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - personal
    - hspec
