resolver: lts-20.16

extra-deps:

  # Uses media query functions not released yet.
  - git: https://github.com/sebastiaanvisser/clay.git
    commit: e68574333a4f0178e7e5808cbd37a8dd350330ea

  # Uses link check file customization change not merged yet.
  - git: https://github.com/chungyc/hakyll.git
    commit: 8cb5fa5dc36122d53a89530239d9036bc6594ffa

ghc-options:
  "$everything": -O2
