resolver: lts-21.11

extra-deps:

  # Uses properties and media query functions not released yet.
  - git: https://github.com/sebastiaanvisser/clay.git
    commit: f87f86408c01dece3bc0c46057e574b6ee90f6b0

ghc-options:
  "$everything": -O2
