# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-20.8

extra-deps:
- git: git@github.com:chungyc/clay.git
  commit: 452115da3546051c6f250b7c1897a2c0b0b93162

allow-newer: true
