resolver: lts-24.11

extra-deps:

  # Uses properties and media query functions not released yet.
  - git: https://github.com/sebastiaanvisser/clay.git
    commit: 3805af82149e3480f695a00f50067a70eaaead0d
