resolver: lts-20.16

extra-deps:

  # Uses properties and media query functions not released yet.
  - git: https://github.com/sebastiaanvisser/clay.git
    commit: a68f105f3408b524a3d194d0cfc8ccdc78ba3da2

  # Uses link check file customization change not released yet.
  - git: https://github.com/jaspervdj/hakyll.git
    commit: 532eb3bed46e5e5cb2de9628b816346e402ad991

ghc-options:
  "$everything": -O2
