# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-20.8

extra-deps:
- git: git@github.com:chungyc/clay.git
  commit: b3e84fa3bfdb5e33b289856078875a791bbf39a7

allow-newer: true
