name: Build
concurrency: build

on:
  workflow_dispatch:
  push:
    paths:
      - '**.yaml'
      - 'app/**'
      - 'site/**'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Workaround runner image issue
        # https://github.com/actions/runner-images/issues/7061
        run: sudo chown -R $USER /usr/local/.ghcup

      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
      
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: stack-${{ hashFiles('package.yaml', 'stack.yaml') }}
          restore-keys: stack-

      - id: cache-build-objects
        uses: actions/cache@v3
        with:
          path: .stack-work
          key: build-${{ hashFiles('app/**', 'src/**') }}
          restore-keys: build-

      - if: ${{ steps.cache-build-objects.outputs.cache-hit == 'true' }}
        id: cache-site
        uses: actions/cache@v3
        with:
          path: |
            _site
            _cache
          key: site-${{ hashFiles('site/**') }}
          restore-keys: site-

      - run: stack build

      - run: stack exec site build

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Run rsync
        run: |
          eval $(ssh-agent -t 1800)
          ssh-add - <<< ${CHUNGYC_SSH_PRIVATE_KEY}
          mkdir ~/.ssh
          echo ${SSH_KNOWN_HOSTS} > ~/.ssh/known_hosts
          stack exec site deploy
        env:
          CHUNGYC_SSH_PRIVATE_KEY: ${{ secrets.CHUNGYC_SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
