name: Build
concurrency: build

on:
  workflow_dispatch:
  push:
    paths:
      - '**.yaml'
      - 'app/**'
      - 'site/**'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: stack-${{ hashFiles('package.yaml', 'stack.yaml') }}
          restore-keys: stack-

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: .stack-work
          key: build-${{ hashFiles('app/**', 'src/**') }}
          restore-keys: build-

      - run: stack build

      - run: stack exec site build
