name: Build
permissions: read-all

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - 'package.yaml'
      - 'stack.yaml'
      - 'app/**'
      - 'site/**'
      - 'src/**'
      - 'test/**'

jobs:
  build:
    concurrency: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.stack
          key: stack-${{ hashFiles('package.yaml', 'stack.yaml') }}
          restore-keys: stack-

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: .stack-work
          key: build-${{ hashFiles('app/**', 'src/**', 'test/**') }}
          restore-keys: build-

      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true

      - name: Build and test
        run: stack build --test --haddock --no-haddock-deps --haddock-arguments=--no-warnings

      - name: Build site
        run: stack exec site build

      - id: paths
        name: Get paths
        run: |
          echo "executable=$(stack path --local-install-root)/bin/site" >> $GITHUB_OUTPUT
          echo "docs=$(stack path --local-doc-root --no-haddock-deps)/personal-$(stack query locals personal version)" >> $GITHUB_OUTPUT

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: ${{ steps.paths.outputs.executable }}

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ${{ steps.paths.outputs.docs }}

      - name: Upload site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
          include-hidden-files: true

  deploy-site:
    if: github.ref_name == 'main'
    needs: build
    concurrency: deploy-site
    runs-on: ubuntu-latest

    steps:

      - name: Download site
        uses: actions/download-artifact@v5
        with:
          name: site
          path: _site

      - name: Download executable
        uses: actions/download-artifact@v5
        with:
          name: executable

      - name: rsync
        run: |
          eval $(ssh-agent -t 1800)
          ssh-add - <<< ${CHUNGYC_SSH_PRIVATE_KEY}
          mkdir ~/.ssh
          echo ${SSH_KNOWN_HOSTS} > ~/.ssh/known_hosts
          chmod u+x site
          ./site deploy
        env:
          CHUNGYC_SSH_PRIVATE_KEY: ${{ secrets.CHUNGYC_SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

  deploy-docs:
    if: github.ref_name == 'main'
    needs: build
    concurrency: deploy-docs
    runs-on: ubuntu-latest

    # Permissions needed to deploy to GitHub Pages.
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: docs
          path: _site

      - uses: actions/upload-pages-artifact@v3

      - uses: actions/deploy-pages@v4
