name: Deploy Documentation
permissions: read-all

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy:
    needs: build
    concurrency: deploy-docs
    runs-on: ubuntu-latest

    # Permissions needed to deploy to GitHub Pages.
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: _site

      - uses: actions/upload-pages-artifact@v1

      - uses: actions/deploy-pages@v1
