on:
  workflow_dispatch
  push:
    branches:
      - 'main'

concurrency: deploy

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
      
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: stack-${{ hashFiles('package.yaml', 'stack.yaml') }}
          restore-keys: stack-

      - uses: actions/cache@v3
        with:
          path: .stack-work
          key: build-${{ hashFiles('app/**', 'src/**') }}
          restore-keys: build-

      - run: stack build

      - run: stack exec site build

      - run: |
          eval $(ssh-agent -t 1800)
          ssh-add - <<< ${CHUNGYC_SSH_PRIVATE_KEY}
          mkdir ~/.ssh
          echo ${SSH_KNOWN_HOSTS} > ~/.ssh/known_hosts
          stack exec site deploy
        env:
          CHUNGYC_SSH_PRIVATE_KEY: ${{ secrets.CHUNGYC_SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
