name: Deploy documentation
concurrency: deploy-docs
permissions: read-all

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: _site

      - uses: actions/upload-pages-artifact
