name: Deploy web site
concurrency: deploy-site
permissions: read-all

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Download site
        uses: actions/download-artifact@v3
        with:
          name: site
          path: _site

      - name: Download executable
        uses: actions/download-artifact@v3
        with:
          name: executable

      - name: rsync
        run: |
          eval $(ssh-agent -t 1800)
          ssh-add - <<< ${CHUNGYC_SSH_PRIVATE_KEY}
          mkdir ~/.ssh
          echo ${SSH_KNOWN_HOSTS} > ~/.ssh/known_hosts
          ./site deploy
        env:
          CHUNGYC_SSH_PRIVATE_KEY: ${{ secrets.CHUNGYC_SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
