name: HLint
permissions: read-all

on:
  workflow_dispatch:
  push:
    paths:
      - '**.hs'
      - '**.lhs'

jobs:
  hlint:
    name: Status check with HLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/hlint-setup@v2
      - uses: haskell/actions/hlint-run@v2
        with:
          path: '["app/", "src/", "test/"]'
          fail-on: warning

  scan:
    if: ${{ github.ref_name == 'main' }}
    name: Scan code with HLint
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write

    steps:
      - uses: actions/checkout@v3

        # A version of HLint with SARIF support has not been released yet,
        # so build the most recent version of HLint ourselves.
      - uses: haskell/actions/setup@v2
      - uses: actions/checkout@v3
        with:
          repository: ndmitchell/hlint
          path: hlint
      - uses: actions/cache@v3
        with:
          path: ~/.cabal
          key: custom-hlint-cabal
      - name: Install hlint
        run: |
          cd hlint
          cabal --overwrite-policy=always install
          cd ..
          rm -rf hlint

        # Use branch because it's not ready for a release yet.
      - uses: haskell-actions/hlint-scan@v0.1.0.0
