name: HLint
permissions: {}

on:
  push:
  schedule:
  - cron: '4 5 13 * *'

jobs:
  hlint:
    name: Scan code with HLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/hlint-scan@v1
