name: HLint
permissions: read-all

on:
  push:
    paths:
      - '**.hs'

jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/hlint-setup@v2
      - uses: haskell/actions/hlint-run@v2
        with:
          path: '["app/", "src/", "test/"]'
          fail-on: warning
