name: Ormolu
permissions: read-all

on:
  push:
    paths:
      - '**.hs'

jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v10
