name: Ormolu
permissions:
  contents: read
  actions: read

on:
  push:
    paths:
      - '**.hs'

jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v14
        with:
          # Set language and extensions explicitly
          # to accommodate Haskell code generating the site.
          respect-cabal-files: false
          extra-args: '-o -XGHC2021 -o -XOverloadedStrings'
